name: Generate Snake

on:
  schedule:               # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch:      # Manual run from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Eskinder185
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

